"""CLI entry point for my_cli_app.

This module defines the Typer `app` instance and all commands.
Users can invoke it via `python -m my_cli_app` or the console script
`my-cli` generated by Poetry.
"""

import typer

app = typer.Typer(add_completion=False, help="My CLI App built with Typer.")


def _root_callback() -> None:
    """Entry point when running without subcommands."""
    typer.echo("El entorno, melón :)")


@app.command()
def hello(name: str = "world") -> None:  # noqa: D401
    """Say hello to *NAME* (defaults to *world*)."""
    typer.echo(f"Hello, {name}!")


# Typer allows setting a callback executed when no subcommand is provided
app.callback(invoke_without_command=True)(_root_callback)


def main() -> None:  # pragma: no cover
    """Call [`app`](#app) when module is executed as a script."""
    app()


if __name__ == "__main__":  # pragma: no cover
    main()
